###
GET http://localhost:3000/api/users
Authorization: Bearer token

###
GET http://localhost:3000/api/user/14
Authorization: Bearer token

### 
DELETE http://localhost:3000/api/user/13
Authorization: Bearer token
###
PATCH http://localhost:3000/api/user/8 HTTP/1.1
Authorization: Bearer token
content-type: application/json

{
    "username": "user2",
    "password": "password2"
}

###
POST http://localhost:3000/api/user/new HTTP/1.1
Authorization: Bearer token
content-type: application/json

{
    "username": "user1",
    "password": "password",
    "email": "email@mail.com"
}

###
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "password"
}

###
POST http://localhost:3000/auth/registration HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "password",
    "email": "email@mail.com"
}